### PR TITLE
Fix preorder iteration

### LINKED ISSUE #185: Error in node preorder
When we first visit a new root, we are forgetting to add all of its children to the node stack.

### PR DESCRIPTION
**Pull request by molpopgen**
* Add nodes right-to-left
* Add children of next root

Fixes #185

### CODE REVIEW

File: forrustts-tables-trees/src/trees.rs [hunk 1]
```diff
@@ -96,15 +96,20 @@ impl NodeIterator for PreorderNodeIterator<'_> {
         self.current_node_ = self.node_stack.pop();
         match self.current_node_ {
             Some(u) => {
-                let mut c = self.tree.left_child(u).unwrap();
+                let mut c = self.tree.right_child(u).unwrap();
```
Comment (molpopgen) [inline forrustts-tables-trees/src/trees.rs]: We need to add tests that we get the exact order out that we expect, correct number and ID of roots in each tree, etc..
