### PR TITLE
Fix mutation table sorting.  Add more table validation.

### LINKED ISSUE #111: Table validation
Need mutation/site table validation, too.

### PR DESCRIPTION
**Pull request by molpopgen**

### CODE REVIEW

File: examples/forward_simulation.rs [hunk 1]
```diff
@@ -669,16 +669,13 @@ fn main() {
...
-        false => {
-            let _ = tskit_tables.build_index().unwrap();
-        }
-    };
-
     add_tskit_mutation_site_tables(&tables, &origin_times, g.into(), &mut tskit_tables);
 
-    tskit_tables
-        .dump(&outfile, tskit::TableOutputOptions::default())
+    let ts = match tskit_tables.tree_sequence(tskit::TreeSequenceFlags::BUILD_INDEXES) {
```
Comment (molpopgen) [inline examples/forward_simulation.rs:637]: This doesn't allow us to dump un-simplified tables.  We need tests for this, too.
